### ISSUE TITLE
Aktivitas Daily Scrum

### ISSUE THREAD

**Issue by Rismayanti20803** [Rismayanti20803/ppl#10]

**Comment by Ratnasari0206** [comment]
di pertemuan pertama kami membuat akun GITHUB secara mandiri

**Comment by Ratnasari0206** [comment]
dan membuat backlog dan spring backlog

**Comment by Ratnasari0206** [comment]
selanjutnya di pertemuan kedua kami  melakukan wawancara pertama
dan di pertemuan ketiga membeli bahan bahan produk yang sesuai dengan requirement
dan di pertemuan keempat membuat atau mendesaign produk sesuai dengan hasil wawancara pada custemer
di pertemuan kelima melakukan wawancara kedua
dan di pertemuan akhir  membuat vidio presentasi hasil kerja kelompok
