### ISSUE TITLE
Dokumentasi Keterlibatan Tim Pengembangaan

### ISSUE THREAD

**Issue by Rismayanti20803** [Rismayanti20803/ppl#13]

**Comment by Ratnasari0206** [comment]
![Image](https://github.com/Rismayanti20803/ppl/assets/155230956/fd28ec5f-b043-41e0-9954-57acf43e214f)



![Image](https://github.com/Rismayanti20803/ppl/assets/155230956/a60de5e5-6238-435e-a661-095e3f168cf3)
