### ISSUE TITLE
dokumentasi rekaman wawancara

### ISSUE THREAD

**Issue by Rismayanti20803** [Rismayanti20803/ppl#16]

**Comment by Ratnasari0206** [comment]
![Image](https://github.com/Rismayanti20803/ppl/assets/155230956/5e2e073a-6ae1-46bd-9043-9beaa7b4c777)



![Image](https://github.com/Rismayanti20803/ppl/assets/155230956/efcd1684-e5fc-4444-b174-07314a1737d7)

**Comment by Ratnasari0206** [comment]
[DESKRIPSI WAWANCARA PERTAMA KEDUA.docx](https://github.com/Rismayanti20803/ppl/files/13928292/DESKRIPSI.WAWANCARA.PERTAMA.KEDUA.docx)
