### ISSUE TITLE
Transkrip Wawancara

### ISSUE THREAD

**Issue by Rismayanti20803** [Rismayanti20803/ppl#17]

**Comment by Ratnasari0206** [comment]
meminta waktu kepada custemer untuk melakukan wawancara pertama
menanyakan perihal keinginan custemer terkait produk yg kami kembangkan yaitu GIFT BUKET
pertanyaan kepada curtemer
1. Jika ingin memberikan gift buket kepada seseorang ingin yang seperti apa?
2. Mau isian apa?
3. Bentuknya mau yang seperti apa?
4. Mau tema warna yang seperti apa?
5. Dan untuk ukurannya mau yang seberapa?
