### ISSUE TITLE
Dokumentasi Aktivitas ‘Brainstorming’ Untuk Menentukan Desain Produk.

### ISSUE THREAD

**Issue by Rismayanti20803** [Rismayanti20803/ppl#20]

**Comment by veririswanto** [comment]
Desain produk 
buket pertama:  Susunan buket boneka diletakkan di tengah-tengah buket, dibawah boneka disusun juga bunga hortensia berwarna soft pink. Selanjutnya dibagian atas bunga dan disamping kanan kiri boneka ditambahkan juga coklat silverqueen, dikanan 1 dan dikiri 1. kemudian ditambahkan juga uang koin 500 rupiah  yang dibentuk seperti bunga, ada 5 bunga koin yang disusun disetiap sisinya, bagian atas 1 bagian tengah kanan dikir 1 dan bawah kanan kiri. Kemudian ditambahkan juga bunga baby breath disetiap sisi sisinya dan ruang yang kosong. Setelah selesai menyusun isi buketnya, selanjutnya bagian wrapping, bentuk wrapping yang dibuat ada bentuk satu sisi, dimana bagian bagian samping kanan kiri dan belakangnya ditutup kertas wrapping.

buket kedua: Susunan buket rokok diletakkan menjadi 3 tingkatan yaitu bagian bawah 2 bungkus rokok, bagian tengah 3 bungkus rokok, dan untuk bagian atas terdapat 4 bungkus rokok yang disusun seperti piramid terbalik. kemudian menyusun beberapa kopi sachet dibagian bawah rokok sampai samping kanan kiri rokok bagian tengah. Setelah selesai menyusun isi buketnya, selanjutnya bagian wrapping, bentuk wrapping yang dibuat ada bentuk satu sisi, dimana bagian bagian samping kanan kiri dan belakangnya ditutup kertas wrapping.
