### ISSUE TITLE
Low Fidelity Prototype (Sketsa) Produk yang Menunjukkan Desain Awal Produk.

### ISSUE THREAD

**Issue by Rismayanti20803** [Rismayanti20803/ppl#21]

**Comment by veririswanto** [comment]
![Image](https://github.com/Rismayanti20803/ppl/assets/155232301/39b15952-645e-4c0e-89a3-c7227577b8ec)



![Image](https://github.com/Rismayanti20803/ppl/assets/155232301/4395b142-8a52-4323-8ece-bbf2e5f70859)

**Comment by veririswanto** [comment]
![Image](https://github.com/Rismayanti20803/ppl/assets/155232301/4b4fec20-243c-4758-b7bf-efc5a9b7ecbf)



![Image](https://github.com/Rismayanti20803/ppl/assets/155232301/6878a614-5e3f-432f-bbaf-6c12bc0dce66)
