### ISSUE TITLE
Perhitungan Pstimasi Biaya Produksi

### ISSUE THREAD

**Issue by Rismayanti20803** [Rismayanti20803/ppl#23]

**Comment by veririswanto** [comment]
Alat yang digunakan untuk membuat buket
1. Gunting
2. Cutter
3. Lem tembak

Bahan yang dibutuhkan untuk membuat buket beserta harganya
Buket 1
1. Boneka Beard (23.500)
2. Bunga Hortensia (20.300x3=60.900)
4. Bunga beby bearth (13.000x2=26.000)
5. Coklat silverqueen (12.615x2=25.230)
6. Uang koin 500 (500x30=15.000)
7. Busa bunga (6.500)
8. Tusuk sate (1.800)
9. Kertas tisu (2.400x2=4.800)
10. Kertas wrapping pink gliter (2.420x5=12.100)
11. Kertas wrapping pink motif koran (2.420x2=4.840)
12. Pita satin gold (3.250)
13. Lem tembak (1.250)
14. Solatif (650)
Jumlah modal produksi = 185.820
Harga jasa = 164.180
Harga jual produk = 350.000

Buket 2
1. Rokok (40.500x9=364.500)
2. Kopi Good Day (2.500x5=12.500)
3. Kertas tisu (2.400)
4. Kertas wrapping hitam gold (2.420x3=7.260)
5. Pita (3.250)
6. Tusuk sate (1.800)
7. Lem tembak (1.250)
8. Solatif (650)
Jumlah modal produksi = 393.610
Harga jasa = 500.000
Harga jual produk = 106.390
