### ISSUE TITLE
Rekaman Proses Pengujian Produk (wawancara)

### ISSUE THREAD

**Issue by Rismayanti20803** [Rismayanti20803/ppl#27]

**Comment by Ratnasari0206** [comment]
WAWANCARA KEDUA

Tanggapan custemer terhadap buket yang telah jadi apakah sudah sesuai dengan request dari custemer pada wawancara pertama?
Saran apa dari custemer untuk produk buket yang telat dibuat?

Tanggapan kedua custemer terhadap produk yang telah jadi
Untuk buket pria berwarna hitam, itu sangat sesuai karena kebanyakan teman saya juga merokok dan suka kopi, karena rokok dan kopi identik dengan pria. Sedangkan untu buket berwarna pink , sangat sesuai dan sangat cocok karena sudah mencakup request yang saya inginkan.
Kesiampulan yang dapat kami sampaikan yaitu produk yang telah kami buat sudah memenuhi kriteris custemer.
