### ISSUE TITLE
Hasil Analisis Pengujian Produk

### ISSUE THREAD

**Issue by Rismayanti20803** [Rismayanti20803/ppl#28]

**Comment by veririswanto** [comment]
Tanggapan kedua custemer terhadap produk yang telah jadi
Untuk buket pria berwarna hitam, itu sangat sesuai karena kebanyakan teman saya juga merokok dan suka kopi, karena rokok dan kopi identik dengan pria. Sedangkan untu buket berwarna pink , sangat sesuai dan sangat cocok karena sudah mencakup request yang saya inginkan.
Kesiampulan yang dapat kami sampaikan yaitu produk yang telah kami buat sudah memenuhi kriteris custemer.
