### ISSUE TITLE
Dokumentasi Pengujian yang Menunjukkan bahwa Produk Dikembangkan secara Incremental

### ISSUE THREAD

**Issue by Rismayanti20803** [Rismayanti20803/ppl#29]

**Comment by veririswanto** [comment]
Tanggapan kedua custemer terhadap produk yang telah jadi
Untuk buket pria berwarna hitam, itu sangat sesuai karena kebanyakan teman saya juga merokok dan suka kopi, karena rokok dan kopi identik dengan pria. Sedangkan untuk buket berwarna pink , sangat sesuai dan sangat cocok karena sudah mencakup request yang saya inginkan.
Kesiampulan yang dapat kami sampaikan yaitu produk yang telah kami buat sudah memenuhi kriteris custemer.

**Comment by veririswanto** [comment]
![Image](https://github.com/Rismayanti20803/ppl/assets/155232301/25deed1f-f398-4ad7-bf29-4995c130c169)



![Image](https://github.com/Rismayanti20803/ppl/assets/155232301/00d543d1-1f44-47cd-ba3f-55090d85df01)
