### ISSUE TITLE
Dokumentasi Feedback Pengguna terhadap Produk

### ISSUE THREAD

**Issue by Rismayanti20803** [Rismayanti20803/ppl#32]

**Comment by veririswanto** [comment]
Tanggapan kedua custemer terhadap produk yang telah jadi
Untuk buket pria berwarna hitam, itu sangat sesuai karena kebanyakan teman saya juga merokok dan suka kopi, karena rokok dan kopi identik dengan pria. Sedangkan untuk buket berwarna pink , sangat sesuai dan sangat cocok karena sudah mencakup request yang saya inginkan. 
Kesiampulan yang dapat kami sampaikan yaitu produk yang telah kami buat sudah memenuhi kriteris custemer.

**Comment by Rismayanti20803** [comment]
feedback custemer terhadap tim kami yaitu:
1. Berupa ucapan terimakasih.
2. Berupa pujian prodeuk yang telah jadi.
3. Berupa materi.
