### ISSUE TITLE
Aktivitas Sprint Planning

### ISSUE THREAD

**Issue by Rismayanti20803** [Rismayanti20803/ppl#9]

**Comment by Rismayanti20803** [comment]
sprint planning

**Comment by Ratnasari0206** [comment]
1.membuat akun github 
2.membuat backlog pada aplikasi github
3. membuat spring backlog
4.melakukan wawancara pertama
5.mendesaign produk sesuai dengan hasil wawancara pada custemer
6.membeli bahan bahan produk yang sesuai dengan requirement
7.membuat produk 
8.melakukan wawancara kedua
